In [2]:
import scipy.linalg
from numpy import sin, exp

f_x = lambda x: sin(x / 5.0) * exp(x / 10.0) + 5 * exp(-x / 2.0)

polynom_rank = 1
A_1 = [
    [1 ** n for n in range(0, polynom_rank + 1)],
    [15 ** n for n in range(0, polynom_rank + 1)]
]

b_1 = [f_x(1), f_x(15)]

scipy.linalg.solve(A_1, b_1)

array([ 3.43914511, -0.18692825])

In [3]:
polynom_rank = 2
A_2 = [
    [1 ** n for n in range(0, polynom_rank + 1)],
    [8 ** n for n in range(0, polynom_rank + 1)],
    [15 ** n for n in range(0, polynom_rank + 1)]
]

b_2 = [f_x(1), f_x(8), f_x(15)]

scipy.linalg.solve(A_2, b_2)

array([ 3.32512949, -0.06531159, -0.00760104])

In [4]:
polynom_rank = 3
A_3 = [
    [1 ** n for n in range(0, polynom_rank + 1)],
    [4 ** n for n in range(0, polynom_rank + 1)],
    [10 ** n for n in range(0, polynom_rank + 1)],
    [15 ** n for n in range(0, polynom_rank + 1)]
]

b_3 = [f_x(1), f_x(4), f_x(10), f_x(15)]

answer = scipy.linalg.solve(A_3, b_3)
print(answer)

[ 4.36264154 -1.29552587  0.19333685 -0.00823565]


In [5]:
map(lambda x: x.round(2), answer)

In [7]:
f = open('submission2.txt','w')
f.write('4.36264154 -1.29552587  0.19333685 -0.00823565')
f.close()